### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by austinkregel** [Wargog/ManGit#6]
Is there any way I can help you with this project? It would be incredibly useful and since it seems like it would be a php based project it would be invaluable for me to use your project (whenever there is a working demo).

**Comment by Wargog** [comment]
You seem to be a lot better at web design than I, I'm having trouble designing some elements on the settings page. Email me `wargog@omacostudio` and we can get in touch some way off of GitHub so we can keep the issues and PRs clean.
